// pipeline {
//   agent {
//     docker { image 'node:16-alpine' }
//   }
//   stages {
//     stage('Test') {
//       steps {
//         sh 'node --version'
//       }
//     }
//   }
// }


pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'python:latest' }
      }
      steps {
        sh 'python3 demo.py'
      }
    }
  }
}
