// pipeline {
//   agent {
//     docker { image 'node:16-alpine' }
//   }
//   stages {
//     stage('Test') {
//       steps {
//         sh 'node --version'
//       }
//     }
//   }
// }


pipeline {
  agent none
  stages {
    stage('pull python image') {
      agent {
        docker { image 'python3:latest' }
      }
      steps{
        git branch: 'main', url : "https://github.com/apparivenkat/Jenkins-Zero-To-Hero.git"
      }
      steps {
        sh 'python3 my-first-pipeline/demo.py'
      }
    }
  }
}
